# Functions

In [1]:
skill_list = ["Python", "SQL", "Excel"]

len(skill_list)

3

In [4]:
count = 0
for skill in skill_list:
  count += 1

count

3

In [3]:
print("please")

please

In [7]:
import types

# List the built-in functions
print([func for func in dir(__builtins__) if isinstance(getattr(__builtins__, func), types.BuiltinFunctionType)])

['__build_class__', '__import__', 'abs', 'aiter', 'all', 'anext', 'any', 'ascii', 'bin', 'breakpoint', 'callable', 'chr', 'compile', 'delattr', 'dir', 'divmod', 'eval', 'exec', 'format', 'getattr', 'globals', 'hasattr', 'hash', 'hex', 'id', 'isinstance', 'issubclass', 'iter', 'len', 'locals', 'max', 'min', 'next', 'oct', 'open', 'ord', 'pow', 'print', 'repr', 'round', 'setattr', 'sorted', 'sum', 'vars']

In [8]:
data_salaries = [95000, 100000, 85000, 97000, 140000]

In [9]:
min(data_salaries)

85000

In [10]:
max(data_salaries)

140000

In [11]:
sum(data_salaries)

517000

In [12]:
sorted(data_salaries)

[85000, 95000, 97000, 100000, 140000]

# User-Defined Functions

In [32]:
# Calculate total_salary of base_salary * (1 + bonus_rate)

def calculate_salary(base_salary, bonus_rate=.1):

  total_salary = base_salary * (1 + bonus_rate)
  return round(total_salary, 2)

In [34]:
salary_1 = 100000
rate_1 = 0.5

calculate_salary(salary_1, rate_1)

150000.0

In [35]:
print("Print is a special type of Python function")

Print is a special type of Python function

In [36]:
def my_function():
  print("What's up data nerds?")

In [37]:
my_function()

What's up data nerds?

In [38]:
data_scientist_salaries = [95000, 120000, 105000, 90000, 130000]
total_salary = sum(data_scientist_salaries)
min_salary = min(data_scientist_salaries)
max_salary = max(data_scientist_salaries)
print(f"Total Salary: ${total_salary}, Min: ${min_salary}, Max: ${max_salary}")

Total Salary: $540000, Min: $90000, Max: $130000

In [39]:
# Sorted
years_experience = [2, 5, 3, 4, 1]
sorted_experience = sorted(years_experience)
sorted_experience

[1, 2, 3, 4, 5]

In [40]:
def my_experience():
  return 5

In [41]:
my_experience()

5

In [43]:
my_experience()

5

In [44]:
def my_experience():
  pass

In [45]:
# Define a function that accepst a yearly bonus percentage
def my_function(yearly_bonus_percent):

  # Returns the bonus amount based on the salary times the yearly_bonus_percent
  return 70000 * yearly_bonus_percent

# Calling the function
my_function(0.05)

3500.0

In [46]:
# Create a function
def my_function(job_title):
  # Prints the job title
  print(f"The {job_title} has an average salary of $60,000.")

my_function("Data Analyst")

The Data Analyst has an average salary of $60,000.

In [47]:
# Create a function that takes job title and average_salary_arguments
def my_function(job_title, average_salary):
  # Prints the job title and the average salary
  print(f"The {job_title} has an average salary of ${average_salary}.")

In [50]:
my_function("Data Analyst", 85000)

The Data Analyst has an average salary of $85000.

In [51]:
# Calculate total_salary of base_salary * (1 + bonus_rate)
def calculate_salary(base_salary, bonus_rate):
  total_salary = base_salary * (1 + bonus_rate)
  return total_salary

In [52]:
salary_1 = 100000
rate_1 = 0.1

calculate_salary(salary_1, rate_1)

110000.00000000001

In [55]:
def calculate_salary(base_salary, bonus_rate=.1):
  total_salary = base_salary * (1 + bonus_rate)
  return total_salary

In [57]:
salary_1 = 100000

calculate_salary(salary_1, rate_1)

110000.00000000001

In [59]:
salary_1 = 100000

calculate_salary(salary_1, rate_1)

110000.00000000001

In [60]:
salary_1 = 100000
rate_1 = 0.5

calculate_salary(salary_1, rate_1)

150000.0

In [63]:
def analyze_skills(skill1, salary1, skill2, salary2):
  """
  Print job titles with their corresponding average salaries using explicitly named parameters.

  :param skill1: The first job title or skill.
  :param salary1: The average salary for the first job title or skill.
  :param skill2: The second job title or skill.
  :param salary2: The average salary for the second job title or skill.
  """
  print('Job Title and Average Salary Analysis:')
  print(f"- {skill1}: ${salary1:,}")
  print(f"- {skill2}: ${salary2:,}")

# Calling the function with job titles and their average salaries as arguments
analyze_skills(skill1="Data Analyst", salary1=60000, skill2="Business Analyst", salary2=65000)

Job Title and Average Salary Analysis:
- Data Analyst: $60,000
- Business Analyst: $65,000

In [66]:
def analyze_skills(*args):
  """
  Print skills with their corresponding average salaries using positional arguments.

  Each argument is expected to be a tuple containing a job title or skill and its average salary.

  :param args: A sequence of tuples, where each tuple contains a job title or skill and its average salary.
  """
  print("Job Title and Average Salary Analyses:")
  for skill_salary_pair in args:
    skill, salary = skill_salary_pair
    print(f"- {skill}: ${salary:,}")

# Calling the function with tuples of job titles and their average salaries
analyze_skills(("Data Analyze", 60000), ("Business Analyze", 65000), ("Data Engineer", 90000))

Job Title and Average Salary Analyses:
- Data Analyze: $60,000
- Business Analyze: $65,000
- Data Engineer: $90,000

In [69]:
def analyze_skills(**skills_salaries):
    """
    Print skills with their corresponding average salaries using keyword arguments.

    :param skills_salaries: Keyword arguments where keys are skills or job titles, and values are average salaries.
    """
    print('Skill and Average Salary Analysis:')
    for skill, salary in skills_salaries.items():
        print(f'- {skill}: ${salary:,}')

# Calling the function with keyword arguments for skills and their average salaries
analyze_skills(Data_Analyst=60000, Business_Analyst=65000, Data_Engineer=90000)

Skill and Average Salary Analysis:
- Data_Analyst: $60,000
- Business_Analyst: $65,000
- Data_Engineer: $90,000

# Problems

In [72]:
# Job Title Contains

def job_title_contains(job, word):
  if word in job:
    return True
  else:
    return False

job_title = 'Data Scientist'
keyword = 'Data'

job_title_contains(job_title, keyword)

True

In [74]:
# Average Salary
salaries = [95000, 120000, 105000, 90000, 130000]

def avg_salary(salaries):
  total_salary = 0
  for salary in salaries:
    total_salary += salary

  return total_salary / len(salaries)

avg_salary(salaries)

108000.0

In [75]:
# Salary Statistics
salaries = [95000, 120000, 105000, 90000, 130000]

def salary_statistics(salaries):
  total_salary = sum(salaries)
  min_salary = min(salaries)
  max_salary = max(salaries)
  print(f"Total Salary: ${total_salary}, Min: ${min_salary}, Max: ${max_salary}")

salary_statistics(salaries)

Total Salary: $540000, Min: $90000, Max: $130000

In [76]:
# Job Posting Summary
job_postings = [
    {'title': 'Data Scientist', 'location': 'New York', 'salary': 95000},
    {'title': 'Data Analyst', 'location': 'San Francisco', 'salary': 85000},
    {'title': 'Machine Learning Engineer', 'location': 'New York', 'salary': 115000}
]

def job_post_sum(*args):
  print("Job Posting Summary")
  for job_post in job_postings:
    title, location, salary = job_post.values()
    print(f"- {title} located in {location}. Salary: ${salary:,}")

job_post_sum(job_postings)

Job Posting Summary
- Data Scientist located in New York. Salary: $95,000
- Data Analyst located in San Francisco. Salary: $85,000
- Machine Learning Engineer located in New York. Salary: $115,000

In [77]:
# Check if a Word is in Job Title

def job_title_contains(job_title, keyword):
    if keyword in job_title:
      return True
    else:
      return False

# Example usage:
job_title = "Software Engineer"
keyword = "Engineer"
print(job_title_contains(job_title, keyword))  # Expected output: True

True

In [78]:
# Calculate the Average Salary

def average_salary(salaries):
    total_salary = sum(salaries)
    return total_salary / len(salaries)

# Example usage:
salaries = [75000, 95000, 110000, 120000]
print(average_salary(salaries))  # Expected output: (some average value)

100000.0

In [79]:
# Check if a word is in a sentence

def contains_word(sentence, word):
    if word in sentence:
      return True
    else:
      return False

# Example usage:
sentence = "Learning Python is fun and rewarding."
word = "Python"

contains_word(sentence, word)

True

In [82]:
# Calculate the average age
def average_age(ages):
  print(sum(ages) / len(ages))

ages = [22, 25, 30, 40, 35]
average_age(ages)

30.4

In [88]:
# Calculate temperature statistics
def temperature_stats(t):
  min_temp = min(t)
  max_temp = max(t)
  avg_temp = sum(t) / len(t)
  print(f"Todays Temperature Statistics are:\nMinimum Temperature: {min_temp}°F\nMaximum Temperature: {max_temp}°F\nAverage Temperature: {avg_temp}°F")

temperatures = [15.5, 20.3, 18.8, 22.0, 16.4]
temperature_stats(temperatures)

Todays Temperature Statistics are:
Minimum Temperature: 15.5°F
Maximum Temperature: 22.0°F
Average Temperature: 18.6°F

In [94]:
# Summarize a list of students
def summarize_students(students):
  for student in students:
    name, age, grade = student.values()
    print(f"Name: {name}, Grade: {grade}")
    print(f'{student["name"]} - Grade: {student["grade"]}')

students = [
    {'name': 'Alice', 'age': 20, 'grade': 'A'},
    {'name': 'Bob', 'age': 22, 'grade': 'B'},
    {'name': 'Charlie', 'age': 21, 'grade': 'A+'}
]
summarize_students(students)

Name: Alice, Grade: A
Alice - Grade: A
Name: Bob, Grade: B
Bob - Grade: B
Name: Charlie, Grade: A+
Charlie - Grade: A+