In [1]:
!pip install datasets

Collecting datasets
  Downloading datasets-3.3.2-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.17.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.10.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.13)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.4.6)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.3.2-py3-none-any.whl (485 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.4/485.4 kB 19.0 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 11.9 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 15.9 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 22.1 MB/s eta 0:00:00
Installing collected packages: xxhash, dill, multiprocess, datasets
Successfully installed datasets-3.3.2 dill-0.3.8 multiprocess-0.70.16 xxhash-3.5.0

In [2]:
import pandas as pd
from datasets import load_dataset

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

data_jobs.csv:   0%|          | 0.00/231M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

In [3]:
df.describe()

                     job_posted_date  salary_year_avg  salary_hour_avg
count                         785741     22003.000000     10662.000000
mean   2023-06-25 16:02:11.860248576    123286.274072        47.016598
min              2023-01-01 00:00:04     15000.000000         8.000000
25%              2023-03-20 10:05:48     90000.000000        27.500000
50%              2023-06-29 06:11:38    115000.000000        45.980000
75%              2023-09-27 01:01:16    150000.000000        61.159996
max              2023-12-31 23:59:58    960000.000000       391.000000
std                              NaN     48312.449482        21.890738

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

In [5]:
df['salary_year_avg'].mean()

123286.27407182401

In [6]:
df['salary_year_avg'].min()

15000.0

In [7]:
min_salary = df['salary_year_avg'].idxmin()

In [8]:
df.iloc[min_salary]

job_title_short                                              Data Engineer
job_title                                           Data Engineer - Hadoop
job_location                                                        Brazil
job_via                                                       via LinkedIn
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                     Brazil
job_posted_date                                        2023-12-09 10:05:30
job_no_degree_mention                                                 True
job_health_insurance                                                 False
job_country                                                         Brazil
salary_rate                                                           year
salary_year_avg                                                    15000.0
salary_hour_avg                                                        NaN
company_name                                               Net2Source Inc.
job_skills               ['java', 'python', 'oracle', 'aws', 'hadoop', ...
job_type_skills          {'cloud': ['oracle', 'aws'], 'libraries': ['ha...
Name: 665729, dtype: object

In [9]:
df['job_title_short'].unique()

array(['Senior Data Engineer', 'Data Analyst', 'Data Engineer',
       'Business Analyst', 'Data Scientist', 'Machine Learning Engineer',
       'Senior Data Analyst', 'Cloud Engineer', 'Senior Data Scientist',
       'Software Engineer'], dtype=object)

In [10]:
df['job_title_short'].value_counts()

job_title_short
Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Business Analyst              49063
Software Engineer             44929
Senior Data Engineer          44563
Senior Data Scientist         36957
Senior Data Analyst           29216
Machine Learning Engineer     14080
Cloud Engineer                12331
Name: count, dtype: int64

In [11]:
df.groupby('job_title_short')['salary_year_avg'].min()

job_title_short
Business Analyst             16500.0
Cloud Engineer               42000.0
Data Analyst                 25000.0
Data Engineer                15000.0
Data Scientist               27000.0
Machine Learning Engineer    30000.0
Senior Data Analyst          30000.0
Senior Data Engineer         35000.0
Senior Data Scientist        45000.0
Software Engineer            28000.0
Name: salary_year_avg, dtype: float64

In [12]:
df.groupby(['job_title_short', 'job_country'])['salary_year_avg'].median()

job_title_short    job_country
Business Analyst   Afghanistan        NaN
                   Albania            NaN
                   Algeria            NaN
                   Angola             NaN
                   Argentina      71100.0
                                   ...
Software Engineer  Venezuela          NaN
                   Vietnam        53600.0
                   Yemen              NaN
                   Zambia             NaN
                   Zimbabwe           NaN
Name: salary_year_avg, Length: 1387, dtype: float64

In [13]:
df.groupby('job_title_short')[['salary_year_avg', 'salary_hour_avg']].median()

                           salary_year_avg  salary_hour_avg
job_title_short
Business Analyst                   85000.0        40.362499
Cloud Engineer                     90000.0        40.000000
Data Analyst                       90000.0        32.615002
Data Engineer                     125000.0        58.500000
Data Scientist                    127500.0        47.500000
Machine Learning Engineer         106415.0        47.535000
Senior Data Analyst               111175.0        47.500000
Senior Data Engineer              147500.0        61.500000
Senior Data Scientist             155500.0        47.620003
Software Engineer                  99150.0        47.560001

In [14]:
df.groupby('job_title_short')['salary_year_avg'].agg(['min', 'max', 'median'])

                               min       max    median
job_title_short
Business Analyst           16500.0  387460.0   85000.0
Cloud Engineer             42000.0  280000.0   90000.0
Data Analyst               25000.0  650000.0   90000.0
Data Engineer              15000.0  525000.0  125000.0
Data Scientist             27000.0  960000.0  127500.0
Machine Learning Engineer  30000.0  325000.0  106415.0
Senior Data Analyst        30000.0  425000.0  111175.0
Senior Data Engineer       35000.0  425000.0  147500.0
Senior Data Scientist      45000.0  890000.0  155500.0
Software Engineer          28000.0  375000.0   99150.0

In [15]:
df.describe()

                     job_posted_date  salary_year_avg  salary_hour_avg
count                         785741     22003.000000     10662.000000
mean   2023-06-25 16:02:11.860248576    123286.274072        47.016598
min              2023-01-01 00:00:04     15000.000000         8.000000
25%              2023-03-20 10:05:48     90000.000000        27.500000
50%              2023-06-29 06:11:38    115000.000000        45.980000
75%              2023-09-27 01:01:16    150000.000000        61.159996
max              2023-12-31 23:59:58    960000.000000       391.000000
std                              NaN     48312.449482        21.890738

In [16]:
df['salary_year_avg'].describe()

count     22003.000000
mean     123286.274072
std       48312.449482
min       15000.000000
25%       90000.000000
50%      115000.000000
75%      150000.000000
max      960000.000000
Name: salary_year_avg, dtype: float64

In [17]:
df.count()

job_title_short          785741
job_title                785740
job_location             784696
job_via                  785733
job_schedule_type        773074
job_work_from_home       785741
search_location          785741
job_posted_date          785741
job_no_degree_mention    785741
job_health_insurance     785741
job_country              785692
salary_rate               33067
salary_year_avg           22003
salary_hour_avg           10662
company_name             785723
job_skills               668704
job_type_skills          668704
dtype: int64

In [18]:
df['salary_year_avg'].max()

960000.0

In [19]:
df['salary_year_avg'].idxmax()

554784

In [20]:
df.iloc[55784]

job_title_short                      Data Analyst
job_title                Data Analyste métier H/F
job_location                         Lyon, France
job_via                              via Jobijoba
job_schedule_type                       Full-time
job_work_from_home                          False
search_location                            France
job_posted_date               2023-05-15 07:21:19
job_no_degree_mention                        True
job_health_insurance                        False
job_country                                France
salary_rate                                  None
salary_year_avg                               NaN
salary_hour_avg                               NaN
company_name                                Apave
job_skills                                   None
job_type_skills                              None
Name: 55784, dtype: object

In [21]:
df.describe()

                     job_posted_date  salary_year_avg  salary_hour_avg
count                         785741     22003.000000     10662.000000
mean   2023-06-25 16:02:11.860248576    123286.274072        47.016598
min              2023-01-01 00:00:04     15000.000000         8.000000
25%              2023-03-20 10:05:48     90000.000000        27.500000
50%              2023-06-29 06:11:38    115000.000000        45.980000
75%              2023-09-27 01:01:16    150000.000000        61.159996
max              2023-12-31 23:59:58    960000.000000       391.000000
std                              NaN     48312.449482        21.890738

In [22]:
df['salary_year_avg'].describe()

count     22003.000000
mean     123286.274072
std       48312.449482
min       15000.000000
25%       90000.000000
50%      115000.000000
75%      150000.000000
max      960000.000000
Name: salary_year_avg, dtype: float64

In [23]:
df.count()

job_title_short          785741
job_title                785740
job_location             784696
job_via                  785733
job_schedule_type        773074
job_work_from_home       785741
search_location          785741
job_posted_date          785741
job_no_degree_mention    785741
job_health_insurance     785741
job_country              785692
salary_rate               33067
salary_year_avg           22003
salary_hour_avg           10662
company_name             785723
job_skills               668704
job_type_skills          668704
dtype: int64

In [24]:
df['salary_year_avg'].count()

22003

In [25]:
df['salary_year_avg'].mode()

0    90000.0
Name: salary_year_avg, dtype: float64

In [26]:
df['salary_year_avg'].idxmax()

554784

In [27]:
df.iloc[554784]

job_title_short                                           Data Scientist
job_title                                                 Data Scientist
job_location                                                 Madison, SD
job_via                                    via Cooperative Career Center
job_schedule_type                                              Full-time
job_work_from_home                                                 False
search_location                                  Illinois, United States
job_posted_date                                      2023-05-04 19:06:06
job_no_degree_mention                                              False
job_health_insurance                                                True
job_country                                                United States
salary_rate                                                         year
salary_year_avg                                                 960000.0
salary_hour_avg                                                      NaN
company_name                 East River Electric Power Cooperative, Inc.
job_skills                                ['java', 'c++', 'python', 'r']
job_type_skills          {'programming': ['java', 'c++', 'python', 'r']}
Name: 554784, dtype: object

In [28]:
df['job_title_short'].value_counts()

job_title_short
Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Business Analyst              49063
Software Engineer             44929
Senior Data Engineer          44563
Senior Data Scientist         36957
Senior Data Analyst           29216
Machine Learning Engineer     14080
Cloud Engineer                12331
Name: count, dtype: int64

In [29]:
df.groupby('job_title_short')['salary_year_avg'].mean()

job_title_short
Business Analyst              91082.612833
Cloud Engineer               111268.453846
Data Analyst                  93841.907854
Data Engineer                130125.604250
Data Scientist               135988.837171
Machine Learning Engineer    126774.315972
Senior Data Analyst          113911.363665
Senior Data Engineer         145840.611624
Senior Data Scientist        154206.292996
Software Engineer            113393.760054
Name: salary_year_avg, dtype: float64

In [30]:
df.groupby('job_title_short')['salary_year_avg'].median()

job_title_short
Business Analyst              85000.0
Cloud Engineer                90000.0
Data Analyst                  90000.0
Data Engineer                125000.0
Data Scientist               127500.0
Machine Learning Engineer    106415.0
Senior Data Analyst          111175.0
Senior Data Engineer         147500.0
Senior Data Scientist        155500.0
Software Engineer             99150.0
Name: salary_year_avg, dtype: float64

In [31]:
df.groupby('job_title_short')['salary_year_avg'].agg(['max', 'min'])

                                max      min
job_title_short
Business Analyst           387460.0  16500.0
Cloud Engineer             280000.0  42000.0
Data Analyst               650000.0  25000.0
Data Engineer              525000.0  15000.0
Data Scientist             960000.0  27000.0
Machine Learning Engineer  325000.0  30000.0
Senior Data Analyst        425000.0  30000.0
Senior Data Engineer       425000.0  35000.0
Senior Data Scientist      890000.0  45000.0
Software Engineer          375000.0  28000.0

In [32]:
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

In [33]:
# Calculate Mean Salary

print('Total Mean Salary: ',df['salary_year_avg'].mean())
df.groupby('job_title_short')['salary_year_avg'].mean()

Total Mean Salary:  123286.27407182401

job_title_short
Business Analyst              91082.612833
Cloud Engineer               111268.453846
Data Analyst                  93841.907854
Data Engineer                130125.604250
Data Scientist               135988.837171
Machine Learning Engineer    126774.315972
Senior Data Analyst          113911.363665
Senior Data Engineer         145840.611624
Senior Data Scientist        154206.292996
Software Engineer            113393.760054
Name: salary_year_avg, dtype: float64

In [34]:
# Calculate Median Salary

print('Total Median Salary: ',df['salary_year_avg'].median())
df.groupby('job_title_short')['salary_year_avg'].median()

Total Median Salary:  115000.0

job_title_short
Business Analyst              85000.0
Cloud Engineer                90000.0
Data Analyst                  90000.0
Data Engineer                125000.0
Data Scientist               127500.0
Machine Learning Engineer    106415.0
Senior Data Analyst          111175.0
Senior Data Engineer         147500.0
Senior Data Scientist        155500.0
Software Engineer             99150.0
Name: salary_year_avg, dtype: float64

In [35]:
# Average Hourly Salary by Job Title

df.groupby('job_title_short')['salary_hour_avg'].mean()

job_title_short
Business Analyst             42.723415
Cloud Engineer               45.560715
Data Analyst                 38.106918
Data Engineer                57.196998
Data Scientist               49.361403
Machine Learning Engineer    48.477935
Senior Data Analyst          47.661218
Senior Data Engineer         62.848496
Senior Data Scientist        54.105631
Software Engineer            46.452019
Name: salary_hour_avg, dtype: float64

In [36]:
# Job With Lowest Salary
df.iloc[df['salary_year_avg'].idxmin()]

job_title_short                                              Data Engineer
job_title                                           Data Engineer - Hadoop
job_location                                                        Brazil
job_via                                                       via LinkedIn
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                     Brazil
job_posted_date                                        2023-12-09 10:05:30
job_no_degree_mention                                                 True
job_health_insurance                                                 False
job_country                                                         Brazil
salary_rate                                                           year
salary_year_avg                                                    15000.0
salary_hour_avg                                                        NaN
company_name                                               Net2Source Inc.
job_skills               ['java', 'python', 'oracle', 'aws', 'hadoop', ...
job_type_skills          {'cloud': ['oracle', 'aws'], 'libraries': ['ha...
Name: 665729, dtype: object

In [37]:
# Job Count by Country

df.groupby('job_country')['job_country'].count()

job_country
Afghanistan      16
Albania         119
Algeria         111
Angola           11
Argentina      8736
               ...
Venezuela        69
Vietnam        2414
Yemen            10
Zambia          104
Zimbabwe         81
Name: job_country, Length: 160, dtype: int64

In [38]:
df.iloc[df['salary_year_avg'].idxmax()]

job_title_short                                           Data Scientist
job_title                                                 Data Scientist
job_location                                                 Madison, SD
job_via                                    via Cooperative Career Center
job_schedule_type                                              Full-time
job_work_from_home                                                 False
search_location                                  Illinois, United States
job_posted_date                                      2023-05-04 19:06:06
job_no_degree_mention                                              False
job_health_insurance                                                True
job_country                                                United States
salary_rate                                                         year
salary_year_avg                                                 960000.0
salary_hour_avg                                                      NaN
company_name                 East River Electric Power Cooperative, Inc.
job_skills                                ['java', 'c++', 'python', 'r']
job_type_skills          {'programming': ['java', 'c++', 'python', 'r']}
Name: 554784, dtype: object

In [39]:
# Standard Deviation of Salaries

df['salary_year_avg'].std()

48312.44948172934

In [40]:
df[['job_title', 'company_name', 'salary_year_avg']].iloc[df['salary_year_avg'].idxmax()]

job_title                                       Data Scientist
company_name       East River Electric Power Cooperative, Inc.
salary_year_avg                                       960000.0
Name: 554784, dtype: object

In [41]:
# Count of Remote Jobs

df['job_title'].where(df['job_work_from_home'] == True).count()

69552

In [48]:
df.groupby('job_country')['salary_year_avg'].mean()

job_country
Afghanistan              NaN
Albania         79472.500000
Algeria         44550.000000
Angola                   NaN
Argentina      105212.343750
                   ...
Venezuela                NaN
Vietnam         90927.236364
Yemen                    NaN
Zambia          90670.000000
Zimbabwe        67056.666667
Name: salary_year_avg, Length: 160, dtype: float64

In [46]:
help(df.mean)

Help on method mean in module pandas.core.frame:

mean(axis: 'Axis | None' = 0, skipna: 'bool' = True, numeric_only: 'bool' = False, **kwargs) method of pandas.core.frame.DataFrame instance
    Return the mean of the values over the requested axis.

    Parameters
    ----------
    axis : {index (0), columns (1)}
        Axis for the function to be applied on.
        For `Series` this parameter is unused and defaults to 0.

        For DataFrames, specifying ``axis=None`` will apply the aggregation
        across both axes.

        .. versionadded:: 2.0.0

    skipna : bool, default True
        Exclude NA/null values when computing the result.
    numeric_only : bool, default False
        Include only float, int, boolean columns. Not implemented for Series.

    **kwargs
        Additional keyword arguments to be passed to the function.

    Returns
    -------
    Series or scalar

                Examples
                --------
                >>> s = pd.Series([1, 2, 3])
                >>> s.mean()
                2.0

                With a DataFrame

                >>> df = pd.DataFrame({'a': [1, 2], 'b': [2, 3]}, index=['tiger', 'zebra'])
                >>> df
                       a   b
                tiger  1   2
                zebra  2   3
                >>> df.mean()
                a   1.5
                b   2.5
                dtype: float64

                Using axis=1

                >>> df.mean(axis=1)
                tiger   1.5
                zebra   2.5
                dtype: float64

                In this case, `numeric_only` should be set to `True` to avoid
                getting an error.

                >>> df = pd.DataFrame({'a': [1, 2], 'b': ['T', 'Z']},
                ...                   index=['tiger', 'zebra'])
                >>> df.mean(numeric_only=True)
                a   1.5
                dtype: float64